[package]
name = "plux"
description = "Tmux plugin manager written in Rust"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
murus = { path = "../murus" }
serde = { version = "1.0.228", features = ["serde_derive"] }
toml = "0.9.7"
thiserror.workspace = true
