[package]
name = "plux"
description = "Tmux plugin manager written in Rust"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
murus = { version = "0.1.1" }
serde = { version = "1.0.226", features = ["serde_derive"] }
toml = "0.9.5"
thiserror.workspace = true
