[package]
name = "plux"
description = "Tmux plugin manager written in Rust"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
murus = { path = "../murus" }
